### ISSUE TITLE
Release v0.9.4 broke unseal function

### ISSUE THREAD

**Issue by zioproto** [kr1sp1n/node-vault#103]
Since I upgraded from v0.9.3 to v0.9.4 I cannot run anymore the unseal function:

```
> vault.unseal({key: "secretvaluestrippedout" }).catch((err) => { if (err.message !== 'Whatever') {throw err;}})
Promise {
  <pending>,
  domain:
   Domain {
     domain: null,
     _events: { error: [Function: debugDomainError] },
     _eventsCount: 1,
     _maxListeners: undefined,
     members: [] } }
> (node:5465) UnhandledPromiseRejectionWarning: Error: EOF
    at handleVaultResponse (/tmp/node_modules/node-vault/src/index.js:49:21)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)
(node:5465) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 8)
```

**Comment by zioproto** [comment]
@kr1sp1n @tavogel I did a git bisect, and the bad commit that introduces the bug for me is:

```
commit dc6d8fd17ffd2b37d1120d1698153aef264686ae (HEAD, refs/bisect/bad)
Author: Tom Vogel <tom.vogel@telus.com>
Date:   Tue Nov 27 18:15:26 2018 -0800

    Add request body validation
```

thanks for looking into this

**Comment by kr1sp1n** [comment]
@zioproto I tested it and I could reproduce it the following way:

```bash
git checkout dc6d8fd17ffd2b37d1120d1698153aef264686ae
docker-compose up -d vault
node example/init.js
```
The `unseal` response has status 400.
I will have a look at it asap. Thanks for reporting this issue 👍

**Comment by tavogel** [comment]
Request schema is missing for it. I'll add another PR in a moment...

**Comment by kr1sp1n** [comment]
@zioproto @tavogel The fix is released as v0.9.5. Thanks so much for your help 🙏!
