### ISSUE TITLE
Error: Cannot find module './commands.js'

### ISSUE THREAD

**Issue by trevorr** [kr1sp1n/node-vault#29]
A recent, unreleased [commit](https://github.com/kr1sp1n/node-vault/commit/3ed4318652b3e643e1a75c64585360c2384b1bbb), where `main` in `package.json` was changed from `src/index.js` to `dist/index.js`, seems to have broken the loading of this library. The transpiled files are concatenated into a single file, but the `require('./commands.js')` call is still present. I think the fix is simply not concatenating the output.

```
Error: Cannot find module './commands.js'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (.../node_modules/node-vault/dist/index.js:168:16)
```

**Comment by kr1sp1n** [comment]
Thanks @trevorr ! Will have a look at all your PRs in the next days.
